### PR TITLE
Add TypeScript support

### PR DESCRIPTION
**Pull request by brandonpittman**

### CODE REVIEW

**Comment by kristijanhusak** [comment]
Will it work out of the box? I'm currently not using typescript anywhere.

There are few more places where we need to make sure typescript files are found:

* Here - https://github.com/kristijanhusak/vim-js-file-import/blob/master/autoload/jsfileimport/tags.vim#L245 - for each part of if statement
* And here - https://github.com/kristijanhusak/vim-js-file-import/blob/master/autoload/jsfileimport/tags.vim#L235 to be able to consider index.ts also.

**Comment by brandonpittman** [comment]
I did a quick check with an npm package and it worked out of the box. I’ll give it a more thorough check though.

**Comment by kristijanhusak** [comment]
I tested it a bit myself, looks ok. I'll merge this in for now, and do the fixes i suggested.

Thanks!

**Comment by kristijanhusak** [comment]
@brandonpittman I added all the fixes that i mentioned here. Go ahead and give it a try, and let me know if you find any issues.

**Pull request merged**
